(require 'ert)
(require 'el-mock)

(setenv "TZ" "/usr/share/zoneinfo/Europe/London")

(defsubst hash-table-keys (hash-table)
  "Return a list of keys in HASH-TABLE."
  (let ((keys '()))
    (maphash (lambda (k _v) (push k keys)) hash-table)
    keys))

(defsubst hash-table-values (hash-table)
  "Return a list of values in HASH-TABLE."
  (let ((values '()))
    (maphash (lambda (_k v) (push v values)) hash-table)
    values))

(defun orgtrello-tests-hash-equal (hash1 hash2)
  "Compare two hash tables to see whether they are equal.
Deal with nested hash map."
  (catch 'flag (maphash (lambda (x y)
                          (or (and (hash-table-p y)
                                   (orgtrello-tests-hash-equal (gethash x hash2) y))
                              (equal (gethash x hash2) y)
                              (throw 'flag nil)))
                        hash1)
         (throw 'flag t)))

(ert-deftest test-orgtrello-tests-hash-equal ()
  (should (orgtrello-tests-hash-equal (orgtrello-hash-make-properties `((:name . "some other name") (:keyword "TODO")))
                                      (orgtrello-hash-make-properties `((:name . "some other name") (:keyword "TODO")))))
  (should (orgtrello-tests-hash-equal (orgtrello-hash-make-properties `((:keyword "TODO") (:name . "some other name") (:other "1" "2")))
                                      (orgtrello-hash-make-properties `((:name . "some other name") (:other "1" "2") (:keyword "TODO")))))
  (should (orgtrello-tests-hash-equal (orgtrello-hash-make-properties `((:buffername . " *temp*-321986")
                                                                        (:position . 85)
                                                                        (:level . 2)
                                                                        (:keyword . "TODO")
                                                                        (:name . "cbx")
                                                                        (:id . "456")
                                                                        (:due)
                                                                        (:member-ids . "")
                                                                        (:desc)
                                                                        (:tags)
                                                                        (:unknown-properties)))
                                      (orgtrello-hash-make-properties `((:buffername . " *temp*-321986")
                                                                        (:position . 85)
                                                                        (:level . 2)
                                                                        (:keyword . "TODO")
                                                                        (:name . "cbx")
                                                                        (:id . "456")
                                                                        (:due)
                                                                        (:member-ids . "")
                                                                        (:desc)
                                                                        (:tags)
                                                                        (:unknown-properties)))))
  (should (orgtrello-tests-hash-equal (orgtrello-hash-make-properties `((:buffername . " *temp*-321986")
                                                                        (:position . 85)
                                                                        (:level . 2)
                                                                        (:keyword . "TODO")
                                                                        (:name . "cbx")
                                                                        (:id . "456")
                                                                        (:due)
                                                                        (:member-ids . "")
                                                                        (:desc)
                                                                        (:tags)
                                                                        (:unknown-properties)
                                                                        (:parent . ,(orgtrello-hash-make-properties '((:buffername . " *temp*-321986")
                                                                                                                      (:position . 1)
                                                                                                                      (:level . 1)
                                                                                                                      (:keyword . "TODO")
                                                                                                                      (:name . "card title")
                                                                                                                      (:id . "123")
                                                                                                                      (:due)
                                                                                                                      (:member-ids . "")
                                                                                                                      (:desc . "")
                                                                                                                      (:tags)
                                                                                                                      (:unknown-properties)
                                                                                                                      (:parent))))))
                                      (orgtrello-hash-make-properties `((:buffername . " *temp*-321986")
                                                                        (:position . 85)
                                                                        (:level . 2)
                                                                        (:keyword . "TODO")
                                                                        (:name . "cbx")
                                                                        (:id . "456")
                                                                        (:due)
                                                                        (:member-ids . "")
                                                                        (:desc)
                                                                        (:tags)
                                                                        (:unknown-properties)
                                                                        (:parent . ,(orgtrello-hash-make-properties '((:buffername . " *temp*-321986")
                                                                                                                      (:position . 1)
                                                                                                                      (:level . 1)
                                                                                                                      (:keyword . "TODO")
                                                                                                                      (:name . "card title")
                                                                                                                      (:id . "123")
                                                                                                                      (:due)
                                                                                                                      (:member-ids . "")
                                                                                                                      (:desc . "")
                                                                                                                      (:tags)
                                                                                                                      (:unknown-properties)
                                                                                                                      (:parent))))))))
  (should-not (orgtrello-tests-hash-equal (orgtrello-hash-make-properties `((:buffername . " *temp*-321986")
                                                                            (:position . 85)
                                                                            (:level . 2)
                                                                            (:keyword . "TODO")
                                                                            (:name . "cbx")
                                                                            (:id . "456")
                                                                            (:due)
                                                                            (:member-ids . "")
                                                                            (:desc)
                                                                            (:tags)
                                                                            (:unknown-properties)
                                                                            (:parent . ,(orgtrello-hash-make-properties '((:buffername . " *temp*-321986")
                                                                                                                          (:position . 1)
                                                                                                                          (:level . 1)
                                                                                                                          (:keyword . "DONE")
                                                                                                                          (:name . "card title")
                                                                                                                          (:id . "123")
                                                                                                                          (:due)
                                                                                                                          (:member-ids . "")
                                                                                                                          (:desc . "")
                                                                                                                          (:tags)
                                                                                                                          (:unknown-properties)
                                                                                                                          (:parent))))))
                                          ;; keyword in the nested structure is not the same so should fail
                                          (orgtrello-hash-make-properties `((:buffername . " *temp*-321986")
                                                                            (:position . 85)
                                                                            (:level . 2)
                                                                            (:keyword . "TODO")
                                                                            (:name . "cbx")
                                                                            (:id . "456")
                                                                            (:due)
                                                                            (:member-ids . "")
                                                                            (:desc)
                                                                            (:tags)
                                                                            (:unknown-properties)
                                                                            (:parent . ,(orgtrello-hash-make-properties '((:buffername . " *temp*-321986")
                                                                                                                          (:position . 1)
                                                                                                                          (:level . 1)
                                                                                                                          (:keyword . "TODO")
                                                                                                                          (:name . "card title")
                                                                                                                          (:id . "123")
                                                                                                                          (:due)
                                                                                                                          (:member-ids . "")
                                                                                                                          (:desc . "")
                                                                                                                          (:tags)
                                                                                                                          (:unknown-properties)
                                                                                                                          (:parent))))))))
  (should-not (orgtrello-tests-hash-equal (orgtrello-hash-make-properties `((:name . "some other name") (:keyword "TODO")))
                                          (orgtrello-hash-make-properties `((:name . "some other name") (:keyword "DONE"))))))

(ert-deftest test-orgtrello-hash-make-transpose-properties ()
  (should (orgtrello-tests-hash-equal (orgtrello-hash-make-properties `(("some other name" . :name) ("TODO" . :keyword)))
                                      (orgtrello-hash-make-transpose-properties `((:name . "some other name") (:keyword . "TODO"))))))

(ert-deftest test-orgtrello-hash-empty-hash ()
  (should (eq 0 (hash-table-count (orgtrello-hash-empty-hash)))))

(defun org-trello-mode-test ()
  "Trigger org-trello-mode but shaped for the tests (without hooks)."
  (remove-hook 'org-trello-mode-on-hook 'orgtrello-controller-mode-on-hook-fn)
  (remove-hook 'org-trello-mode-off-hook 'orgtrello-controller-mode-off-hook-fn)
  (setq org-trello-mode-on-hook)
  (setq org-trello-mode-off-hook)
  (setq orgtrello-setup-use-position-in-checksum-computation 'please-do-use-position-in-checksum-computation)
  (setq orgtrello-log-level orgtrello-log-no-log)
  (setq org-trello--mode-activated-p t)
  (call-interactively 'org-trello-mode))

(defun orgtrello-tests-prepare-buffer ()
  "orgtrello-tests - Prepare the buffer to receive org-trello data."
  (orgtrello-buffer-indent-card-descriptions)
  (orgtrello-buffer-indent-card-data))

(defmacro orgtrello-tests-with-temp-buffer (text body-test &optional nb-lines-forward)
  `(with-temp-buffer
     (org-mode)
     (insert ,text)
     (forward-line (if ,nb-lines-forward ,nb-lines-forward -1))
     (org-trello-mode-test)
     (orgtrello-controller-setup-properties)
     ,body-test))

(defmacro orgtrello-tests-with-temp-buffer-and-return-buffer-content (text body-test &optional nb-line-forwards)
  `(with-temp-buffer
     (org-mode)
     (insert ,text)
     (forward-line (if ,nb-line-forwards ,nb-line-forwards -1))
     (org-trello-mode-test)
     (orgtrello-controller-setup-properties)
     ,body-test
     (buffer-substring-no-properties (point-min) (point-max))))

(defmacro orgtrello-tests-with-temp-buffer-indented-and-return-buffer-content (text body-test &optional nb-line-forwards)
  `(with-temp-buffer
     (org-mode)
     (insert ,text)
     (forward-line (if ,nb-line-forwards ,nb-line-forwards -1))
     (org-trello-mode-test)
     (orgtrello-controller-setup-properties)
     ,body-test
     (orgtrello-tests-prepare-buffer) ;; force the indentation without hook (show how it's done using hook at runtime)
     (buffer-substring-no-properties (point-min) (point-max))))

(defmacro orgtrello-tests-with-org-buffer (text body-test)
  `(with-temp-buffer
     (insert ,text)
     (org-mode)
     ,body-test))

(provide 'utilities-test)
;;; utilities-test.el ends here
