\input texinfo    @c -*- texinfo -*-
@c %**start of header
@setfilename org-trello.info
@settitle org-trello Manual
@documentencoding UTF-8
@documentlanguage en
@documentdescription
Sync Emacs org-mode with Trello.com.
@end documentdescription
@c %**end of header

@copying
This is the org-trello Manual, edition 0.8.1.a, released 2019-01-30,
written and copyright ©2019 by Daniel Birket.

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
Texts. A copy of the license is included in the section entitled GNU
Free Documentation License.

@end quotation

This manaul describes how to install and use the Emacs package
org-trello, version 0.8.1, released 2018-03-18,
written and copyright ©2013-2017 by Antoine Dumont,
to synchronize org-mode TO-DO lists with @uref{https://trello.com, Trello.com}.

This manual was written with reference to the org-trello source-code,
which begins with this license and non-warranty statement:

@lisp
;;; org-trello.el 
;; Minor mode to synchronize org-mode buffer and trello board

;; Copyright (C) 2013-2017 by Antoine R. Dumont (@@ardumont) 
;; Author: Antoine R. Dumont <antoine.romain.dumont@@gmail.com>
;; Maintainer: Antoine R. Dumont

;; Version: 0.8.1
;; URL: https://github.com/org-trello/org-trello

;; This file is NOT part of GNU Emacs.

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
;; GNU General Public License for more details.
@end lisp
@end copying

@dircategory Emacs
@direntry
* org-trello.           Sync Emacs org-mode with Trello.com.
@end direntry

@finalout
@titlepage
@title org-trello Manual
@subtitle Sync Emacs org-mode with Trello.com.
@author Manual by Daniel Birket
@author Package by Antoine R. Dumont
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top org-trello Manual

Sync Emacs org-mode with Trello.com.

@insertcopying
@end ifnottex

@menu
* About::                        About org-trello
* Installing::                   Installing org-trello
* Connecting::                   Connecting to Trello.com
* Using::                        Using org-trello
* FAQ::                          Frequently-Asked Questions
* Troubleshooting::              Troubleshooting org-trello
* Customizing::                  Customizing org-trello
* Contributing::                 Contributing to org-trello
* GNU GPL::                      GNU General Public License
* GNU FDL::                      GNU Free Documentation License
* Indices::                      Indices

@detailmenu
--- The Detailed Node Listing ---

Using

* Quick Start::                  First Steps with org-trello
* Command Descriptions::         Command Descriptions
* How to…::                      How to Perform Tasks

Command Descriptions

* Summary::                      Summary of Commands
* Connection Cmds::              Connection Commands
* Synch Cmds::                   Synchronization Commands
* Editing Cmds::                 Editing Commands
* Misc Cmds::                    Misc. Commands

Customizing

* Prefix Keys::                  Customizing the Prefix Keybinding
* Individual Keys::              Customizing Individual Key Bindings
* Variables::                    Customizing Variables

Contributing

* Credits::                      Contributor Credits
* Releases::                     Release Notes History

Indices

* Concepts::                     Concepts Index
* Command Index::                Commands Index
* Functions::                    Functions Index
* Variables: Variables (1).      Variables Index

@end detailmenu
@end menu

@node About
@chapter @strong{TODO} About org-trello

Why use org-trello?

@node Installing
@chapter @strong{TODO} Installing org-trello

@cindex org-trello, installing
Installing…

@node Connecting
@chapter @strong{TODO} Connecting to Trello.com

@cindex trello.com, connecting
Connecting…

@node Using
@chapter Using org-trello

@cindex org-trello, using
This section describes how to use org-trello.

@menu
* Quick Start::                  First Steps with org-trello
* Command Descriptions::         Command Descriptions
* How to…::                      How to Perform Tasks
@end menu

@node Quick Start
@section @strong{TODO} Quick Start

@node Command Descriptions
@section Command Descriptions

This section describes all commands.

@menu
* Summary::                      Summary of Commands
* Connection Cmds::              Connection Commands
* Synch Cmds::                   Synchronization Commands
* Editing Cmds::                 Editing Commands
* Misc Cmds::                    Misc. Commands
@end menu

@node Summary
@subsection @strong{WORK} Summary of Commands

All default org-trello key-bindings use the “C-c o” prefix.

@kindex C-c o C-h
@emph{Note:} You may type “C-c o C-h” to display help for most org-trello
key bindings.

@multitable {aaaaaaaaa} {aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
@headitem Keys
@tab Command
@item C-c o C-h
@tab Display help on all key-bindings with C-c o prefix.
@item C-c o v
@tab Display the version of org-trello.
@item C-c o i
@tab Install the Trello.com access key and token.
@item C-c o I
@tab Select an existing Trello board and attach this file to it.
@item C-c o b
@tab Create a new Trello board and attach this file to it.
@item C-c o u
@tab Update this file’s attachment to its Trello board.
@item 
@tab 
@end multitable

@node Connection Cmds
@subsection @strong{TODO} Connection Commands

This section describes the functions used to connect org-trello to
Trello.com and to attach an org file to a Trello board.

@node Synch Cmds
@subsection @strong{WORK} Synchronization Commands

This section describes the synchronization functions.

@kindex C-c o s
@kindex C-u C-c o s
@ftable @code
@item org-trello-sync-buffer
Type “C-c o s” to sync the entire buffer TO the Trello board.@*
Type “C-u C-c o s” to sync the entire buffer FROM the Trello board.
@end ftable

@node Editing Cmds
@subsection @strong{TODO} Editing Commands

This section describes the functions used to edit cards, comments and
list items.

@node Misc Cmds
@subsection @strong{TODO} Misc. Commands

This section describes other functions not listed above.

@node How to…
@section @strong{TODO} How to Perform Tasks

This section is describes how to use commands to perform tasks with org-trello.

@node FAQ
@chapter @strong{TODO} Frequently-Asked Questions

@cindex FAQ
FAQ…

@node Troubleshooting
@chapter @strong{TODO} Troubleshooting org-trello

@cindex troubleshooting
@cindex errors
Troubleshooting…

@node Customizing
@chapter Customizing org-trello

@cindex customizing
This section describes how you may customize org-trello.

@menu
* Prefix Keys::                  Customizing the Prefix Keybinding
* Individual Keys::              Customizing Individual Key Bindings
* Variables::                    Customizing Variables
@end menu

@node Prefix Keys
@section @strong{CHEK} Customizing the Prefix Keybinding

@vindex org-trello-current-prefix-keybinding
By default, org-trello uses the prefix keybinding “C-c o” to begin
(almost) all of its commands. You may change this by customizing the
variable “org-trello-current-prefix-keybinding”.

To customize “org-trello-current-prefix-keybinding”, type “C-h v
org-trello-current-prefix-keybinding RET” to display the help text for this
variable. Then follow the “customize” link on the last line. You
may then use the customize interface to set another prefix keybinding.

@emph{Note:} If org-trello is already running, you must restart emacs after
customizing this variable (or run “M-x org-trello-mode” - @emph{twice}).

You may also change this setting in your emacs initialization file.
For example, to change the org-trello prefix keybinding to “C-c x” add
these lines to your ~/.emacs (or ~/.emacs.d/.init.el) file:

@lisp
(require 'org-trello)
(custom-set-variables '(org-trello-current-prefix-keybinding "C-c x"))
@end lisp

For an example, please see my @uref{https://github.com/ardumont/orgmode-pack/blob/master/orgmode-pack.el#L57, startup file}.

@node Individual Keys
@section @strong{CHEK} Customizing Individual Keybindings

@vindex org-trello-mode-map
To redefine one or more org-trello-mode command keybindings, you should create a
function to define keys in the org-trello-mode-map and hook your
function to the org-trello-mode-hook. This will make org-trello run
your function each time it starts.

@lisp
(require 'org-trello)

(defun def-my-org-trello-keys () "Define my org-trello keys."
  (define-key org-trello-mode-map (kbd "C-c x v") 'org-trello-version)
  (define-key org-trello-mode-map (kbd "C-c x i") 'org-trello-install-key-and-token)
  (define-key org-trello-mode-map (kbd "C-c x I") 'org-trello-install-board-metadata)
  (define-key org-trello-mode-map (kbd "C-c x c") 'org-trello-sync-card)
  (define-key org-trello-mode-map (kbd "C-c x s") 'org-trello-sync-buffer)
  (define-key org-trello-mode-map (kbd "C-c x a") 'org-trello-assign-me)
  (define-key org-trello-mode-map (kbd "C-c x d") 'org-trello-check-setup)
  (define-key org-trello-mode-map (kbd "C-c x D") 'org-trello-delete-setup)
  (define-key org-trello-mode-map (kbd "C-c x b") 'org-trello-create-board-and-install-metadata)
  (define-key org-trello-mode-map (kbd "C-c x k") 'org-trello-kill-entity)
  (define-key org-trello-mode-map (kbd "C-c x K") 'org-trello-kill-cards)
  (define-key org-trello-mode-map (kbd "C-c x a") 'org-trello-archive-card)
  (define-key org-trello-mode-map (kbd "C-c x A") 'org-trello-archive-cards)
  (define-key org-trello-mode-map (kbd "C-c x j") 'org-trello-jump-to-trello-card)
  (define-key org-trello-mode-map (kbd "C-c x J") 'org-trello-jump-to-trello-board)
  (define-key org-trello-mode-map (kbd "C-c x C") 'org-trello-add-card-comments)
  (define-key org-trello-mode-map (kbd "C-c x o") 'org-trello-show-card-comments)
  (define-key org-trello-mode-map (kbd "C-c x l") 'org-trello-show-card-labels)
  (define-key org-trello-mode-map (kbd "C-c x u") 'org-trello-update-board-metadata)
  (define-key org-trello-mode-map (kbd "C-c x h") 'org-trello-help-describing-bindings))

(add-hook 'org-trello-mode-hook 'def-my-org-trello-keys)
@end lisp

@emph{Note:} This will not update the help messages to match your
key-bindings nor remove the default keybindings.

You may add several lines like this one to your hook function to
remove specific existing org-trello keybindings:

@lisp
(define-key org-trello-mode-map (kbd "C-c o v") nil)
@end lisp

@node Variables
@section @strong{TODO} Customizing org-trello Variables

@node Contributing
@chapter Contributing to org-trello

@cindex contributing
Contributing…

@menu
* Credits::                      Contributor Credits
* Releases::                     Release Notes History
@end menu

@node Credits
@section @strong{CHEK} Credits

@cindex credits
@cindex contributors

Many thanks to all the @uref{https://github.com/org-trello/org-trello/graphs/contributors, contributors} to org-trello, including:

@table @asis
@item @uref{https://github.com/dtebbs, @@dtebbs}       
@uref{https://github.com/org-trello/org-trello/pull/173, PR - fix on the card description}
@item @uref{https://github.com/jasom, @@jasom}        
@uref{https://github.com/org-trello/org-trello/pull/175, PR - improvements on the trello card's description rendering}.
@item @uref{https://github.com/nicferrier, @@nicferrier}   
@uref{http://marmalade-repo.org/, marmalade}, @uref{https://github.com/nicferrier/elnode, elnode}, @uref{http://nic.ferrier.me.uk/blog/2012_07/emacs-packages-for-programmers, emacs clean install}@dots{}
@item @uref{https://twitter.com/nicolas_roche, @@nicolas_roche}
logo and the multiple suggestions regarding the web design part.
@item @uref{https://twitter.com/nmassyl, @@nmassyl}      
multiple exchanges on design and functionalities.
@item @uref{https://github.com/purcell, @@purcell}      
various discussions, suggestions regarding packaging on @uref{http://melpa.milkbox.net/, Melpa}
@item @uref{https://github.com/puzan, @@puzan}        
org-trello's el-get recipe
@end table

and thanks to all those that opened @uref{https://github.com/org-trello/org-trello/issues, issues} or @uref{https://github.com/org-trello/org-trello/pulls, pull requests}.

Also, thank you to the entire free-software community world-wide, including the
creators and contributors of Emacs and org-mode.

@node Releases
@section @strong{CHEK} Release Notes

@cindex release notes
@cindex version history
The separate @uref{release-notes.org, release-notes file} records the primary changes in each
release of org-trello. Please also see the @uref{https://github.com/org-trello/org-trello, repository} on GitHub for a
detailed history.

@node GNU GPL
@appendix @strong{DONE} GNU General Public License

@cindex license, software
@include gpl.texi

@node GNU FDL
@appendix @strong{DONE} GNU Free Documentation License

@cindex license, manual
@include fdl.texi

@node Indices
@appendix Indices

This section contains the concepts, commands, functions and variables indices.

@menu
* Concepts::                     Concepts Index
* Command Index::                Commands Index
* Functions::                    Functions Index
* Variables: Variables (1).      Variables Index
@end menu

@node Concepts
@appendixsec Concepts Index

@printindex cp

@node Command Index
@appendixsec Commands Index

@printindex ky

@node Functions
@appendixsec Functions Index

@printindex fn

@node Variables (1)
@appendixsec Variables Index

@printindex vr

@bye