# -*- mode: org; -*-
# Customize Emacs variable org-export-backends to include texinfo,
# then use “C-c C-e i t” to export this file to org-trello.texi.
#+TITLE: org-trello Manual
:METADATA:
#+DATE: 2019-01-30
#+MACRO: DESCR Sync Emacs org-mode with Trello.com.
#+SUBTITLE: {{{DESCR}}}
#+DESCRIPTION: {{{DESCR}}}
#+AUTHOR: Manual by Daniel Birket
#+SUBAUTHOR: Package by Antoine R. Dumont
#+LANGUAGE: en
#+STARTUP: indent

#+TEXINFO_FILENAME: org-trello.info
#+TEXINFO_DIR_CATEGORY: Emacs
#+TEXINFO_DIR_TITLE: org-trello
#+TEXINFO_DIR_DESC: Sync Emacs org-mode with Trello.com.
#+TEXINFO_HEADER: @documentdescription
#+TEXINFO_HEADER: Sync Emacs org-mode with Trello.com.
#+TEXINFO_HEADER: @end documentdescription

#+MACRO: PAK_NAME org-trello
#+MACRO: PAK_AUTHOR Antoine Dumont
#+MACRO: PAK_VERSION 0.8.1
#+MACRO: PAK_RELEASE 2018-03-18
#+MACRO: PAK_COPYRIGHT ©2013-2017
#+MACRO: PAK_DOC_URL http://org-trello.github.io
#+MACRO: PAK_SRC_URL https://github.com/org-trello/org-trello

#+MACRO: DOC_EDITION {{{PAK_VERSION}}}.a
#+MACRO: DOC_EDITOR Daniel Birket
#+MACRO: DOC_COPYRIGHT ©2019
#+MACRO: DOC_SRC_URL https://github.com/daniel-birket/org-trello/tree/texinfo/texinfo
:END:
:OPTIONS:
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:{} arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:t todo:t |:t
:END:
{{{DESCR}}}

#+TEXINFO: @insertcopying
* COPYING
  :PROPERTIES:
  :COPYING:  t
  :END:
This is the {{{TITLE}}}, edition {{{DOC_EDITION}}}, released {{{DATE}}},
written and copyright {{{DOC_COPYRIGHT}}} by {{{DOC_EDITOR}}}.

#+BEGIN_QUOTE
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
Texts. A copy of the license is included in the section entitled GNU
Free Documentation License.
#+END_QUOTE

This manaul describes how to install and use the Emacs package
{{{PAK_NAME}}}, version {{{PAK_VERSION}}}, released {{{PAK_RELEASE}}},
written and copyright {{{PAK_COPYRIGHT}}} by {{{PAK_AUTHOR}}},
to synchronize org-mode TO-DO lists with [[https://trello.com][Trello.com]].

This manual was written with reference to the {{{PAK_NAME}}} source-code,
which begins with this license and non-warranty statement:

#+BEGIN_SRC emacs-lisp
;;; org-trello.el 
;; Minor mode to synchronize org-mode buffer and trello board

;; Copyright (C) 2013-2017 by Antoine R. Dumont (@ardumont) 
;; Author: Antoine R. Dumont <antoine.romain.dumont@gmail.com>
;; Maintainer: Antoine R. Dumont

;; Version: 0.8.1
;; URL: https://github.com/org-trello/org-trello

;; This file is NOT part of GNU Emacs.

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
;; GNU General Public License for more details.
#+END_SRC

* Installing org-trello
  :PROPERTIES:
  :ALT_TITLE: Installing
  :DESCRIPTION: Installing org-trello
  :END:
#+CINDEX: org-trello, installing
Installing…
* Connecting to Trello.com
  :PROPERTIES:
  :ALT_TITLE: Connecting
  :DESCRIPTION: Connecting to Trello.com
  :END:
#+CINDEX: trello.com, connecting
Connecting…
* Using org-trello
  :PROPERTIES:
  :ALT_TITLE: Using
  :DESCRIPTION: Using org-trello
  :END:
#+CINDEX: org-trello, using
This section describes how to use org-trello _after_ connecting an
org-file to a board of Trello.com.
** Summary of Key-Bindings
:PROPERTIES:
:ALT_TITLE: Key-Bindings
:DESCRIPTION: Summary of Key-Bindings
:END:
All default org-trello key-bindings use the “C-c o” prefix.

#+KINDEX: C-c o C-h
/Note:/ You may type “C-c o C-h” to display help for most org-trello
key bindings.

| Keys      | Command                                                     |
|-----------+-------------------------------------------------------------|
| C-c o C-h | Display help on all key-bindings with C-c o prefix.         |
| C-c o v   | Display the version of org-trello.                          |
|-----------+-------------------------------------------------------------|
| C-c o i   | Install the Trello.com access key and token.                |
| C-c o I   | Select an existing Trello board and attach this file to it. |
| C-c o b   | Create a new Trello board and attach this file to it.       |
| C-c o u   | Update this file’s attachment to its Trello board.          |
|           |                                                             |
** Connection Functions 
:PROPERTIES:
:ALT_TEXT: Connect Funcs.
:DESCRIPTION: Connection Functions
:END:
This section describes the functions used to connect org-trello to
Trello.com and to attach an org file to a Trello board.
** Synchronization Functions
:PROPERTIES:
:ALT_TEXT: Synch. Funcs.
:DESCRIPTION: Synchronization Functions
:END:
This section describes the synchronization functions.

#+KINDEX: C-c o s
#+KINDEX: C-u C-c o s
#+ATTR_TEXINFO: :table-type ftable :indic code
- org-trello-sync-buffer :: 
  Type “C-c o s” to sync the entire buffer TO the Trello board.\\
  Type “C-u C-c o s” to sync the entire buffer FROM the Trello board.
** Editing Functions 
:PROPERTIES:
:ALT_TEXT: Editing Funcs.
:DESCRIPTION: Editing Functions
:END:
This section describes the functions used to edit cards, comments and
list items.
** Misc. Functions 
:PROPERTIES:
:ALT_TEXT: Misc. Funcs.
:DESCRIPTION: Miscellaneous Functions
:END:
This section describes other functions not listed above.

* Frequently-Asked Questions
  :PROPERTIES:
  :ALT_TITLE: FAQ
  :DESCRIPTION: Frequently-Asked Questions
  :END:
#+CINDEX: FAQ
FAQ…
* Troubleshooting org-trello
  :PROPERTIES:
  :ALT_TITLE: Troubleshooting
  :DESCRIPTION: Troubleshooting org-trello
  :END:
#+CINDEX: troubleshooting
#+CINDEX: errors
Troubleshooting…
* Customizing org-trello
  :PROPERTIES:
  :ALT_TITLE: Customizing
  :DESCRIPTION: Customizing org-trello
  :END:
#+CINDEX: customizing
This section describes how you may customize org-trello.
** Customizing the Prefix Keybinding
:PROPERTIES:
:ALT_TITLE: Prefix Keys
:DESCRIPTION: Customizing the Prefixx Keybinding
:END:
#+VINDEX: org-trello-current-prefix-keybinding
By default, org-trello uses the prefix keybinding “C-c o” to begin
(almost) all of its commands. You may change this by customizing the
variable “org-trello-current-prefix-keybinding”.

To customize “org-trello-current-prefix-keybinding”, type “C-h v
org-trello-current-prefix-keybinding RET” to display the help text for this
variable. Then follow the “customize” link on the last line. You
may then use the customize interface to set another prefix keybinding.

/Note:/ If org-trello is already running, you must restart emacs after
customizing this variable (or run “M-x org-trello-mode” - /twice/).

You may also change this setting in your emacs initialization file.
For example, to change the org-trello prefix keybinding to “C-c x” add
these lines to your ~/.emacs (or ~/.emacs.d/.init.el) file:

#+BEGIN_SRC emacs-lisp
  (require 'org-trello)
  (custom-set-variables '(org-trello-current-prefix-keybinding "C-c x"))
#+END_SRC

For an example, please see my [[https://github.com/ardumont/orgmode-pack/blob/master/orgmode-pack.el#L57][startup file]].

** Customizing Individual Key Bindings
:PROPERTIES:
:ALT_TITLE: Individual Keys
:DESCRIPTION: Customizing Individual Key Bindings
:END:
#+VINDEX: org-trello-mode-map
To redefine one or more org-trello-mode keys, you should create a
function to define keys in the org-trello-mode-map and hook your
function to the org-trello-mode-hook. This will make org-trello run
your function each time it starts.

#+BEGIN_SRC emacs-lisp
  (require 'org-trello)

  (defun def-my-org-trello-keys () "Define my org-trello keys."
    (define-key org-trello-mode-map (kbd "C-c x v") 'org-trello-version)
    (define-key org-trello-mode-map (kbd "C-c x i") 'org-trello-install-key-and-token)
    (define-key org-trello-mode-map (kbd "C-c x I") 'org-trello-install-board-metadata)
    (define-key org-trello-mode-map (kbd "C-c x c") 'org-trello-sync-card)
    (define-key org-trello-mode-map (kbd "C-c x s") 'org-trello-sync-buffer)
    (define-key org-trello-mode-map (kbd "C-c x a") 'org-trello-assign-me)
    (define-key org-trello-mode-map (kbd "C-c x d") 'org-trello-check-setup)
    (define-key org-trello-mode-map (kbd "C-c x D") 'org-trello-delete-setup)
    (define-key org-trello-mode-map (kbd "C-c x b") 'org-trello-create-board-and-install-metadata)
    (define-key org-trello-mode-map (kbd "C-c x k") 'org-trello-kill-entity)
    (define-key org-trello-mode-map (kbd "C-c x K") 'org-trello-kill-cards)
    (define-key org-trello-mode-map (kbd "C-c x a") 'org-trello-archive-card)
    (define-key org-trello-mode-map (kbd "C-c x A") 'org-trello-archive-cards)
    (define-key org-trello-mode-map (kbd "C-c x j") 'org-trello-jump-to-trello-card)
    (define-key org-trello-mode-map (kbd "C-c x J") 'org-trello-jump-to-trello-board)
    (define-key org-trello-mode-map (kbd "C-c x C") 'org-trello-add-card-comments)
    (define-key org-trello-mode-map (kbd "C-c x o") 'org-trello-show-card-comments)
    (define-key org-trello-mode-map (kbd "C-c x l") 'org-trello-show-card-labels)
    (define-key org-trello-mode-map (kbd "C-c x u") 'org-trello-update-board-metadata)
    (define-key org-trello-mode-map (kbd "C-c x h") 'org-trello-help-describing-bindings))

  (add-hook 'org-trello-mode-hook 'def-my-org-trello-keys)
#+END_SRC

/Note:/ This will not update the help messages to match your
key-bindings nor remove the default keybindings.

You may add several lines like this one to your hook function to
remove specific existing org-trello keybindings:

#+BEGIN_SRC emacs-lisp
    (define-key org-trello-mode-map (kbd "C-c o v") nil)
#+END_SRC
* Contributing to org-trello
  :PROPERTIES:
  :ALT_TITLE: Contributing
  :DESCRIPTION: Contributing to org-trello
  :END:
#+CINDEX: contributing
Contributing…
* Contributor Credits
:PROPERTIES:
:ALT_TITLE: Credits
:DESCRIPTION: Contributor Credits
:APPENDIX: t
:END:
#+CINDEX: credits
#+CINDEX: contributors

Many thanks to all the [[https://github.com/org-trello/org-trello/graphs/contributors][contributors]] to org-trello, including:

- [[https://github.com/dtebbs][@dtebbs]]        :: [[https://github.com/org-trello/org-trello/pull/173][PR - fix on the card description]]
- [[https://github.com/jasom][@jasom]]         :: [[https://github.com/org-trello/org-trello/pull/175][PR - improvements on the trello card's description rendering]].
- [[https://github.com/nicferrier][@nicferrier]]    :: [[http://marmalade-repo.org/][marmalade]], [[https://github.com/nicferrier/elnode][elnode]], [[http://nic.ferrier.me.uk/blog/2012_07/emacs-packages-for-programmers][emacs clean install]]...
- [[https://twitter.com/nicolas_roche][@nicolas_roche]] :: logo and the multiple suggestions regarding the web design part.
- [[https://twitter.com/nmassyl][@nmassyl]]       :: multiple exchanges on design and functionalities.
- [[https://github.com/purcell][@purcell]]       :: various discussions, suggestions regarding packaging on [[http://melpa.milkbox.net/][Melpa]]
- [[https://github.com/puzan][@puzan]]         :: org-trello's el-get recipe

and thanks to all those that opened [[https://github.com/org-trello/org-trello/issues][issues]] or [[https://github.com/org-trello/org-trello/pulls][pull requests]].

Also, thank you to the entire free-software community world-wide, including the
creators and contributors of Emacs and org-mode.

* GNU General Public License
:PROPERTIES:
:ALT_TITLE: GNU GPL
:DESCRIPTION: GNU General Public License
:APPENDIX: t
:END:
#+CINDEX: license, software
#+TEXINFO: @include gpl.texi
* GNU Free Documentation License
:PROPERTIES:
:ALT_TITLE: GNU FDL
:DESCRIPTION: GNU Free Documentation License
:APPENDIX: t
:END:
#+CINDEX: license, manual
#+TEXINFO: @include fdl.texi
* Concepts Index
:PROPERTIES:
:INDEX: cp
:ALT_TITLE: Concepts
:DESCRIPTION: Concepts Index
:APPENDIX: t
:END:
* Key Binding Index
:PROPERTIES:
:INDEX: ky
:ALT_TITLE: Keys
:DESCRIPTION: Key Bindings Index
:APPENDIX: t
:END:
* Functions Index
:PROPERTIES:
:INDEX: fn
:ALT_TITLE: Functions
:DESCRIPTION: Functions Index
:APPENDIX: t
:END:
* Variables Index
:PROPERTIES:
:INDEX: vr
:ALT_TITLE: Variables
:DESCRIPTION: Variables Index
:APPENDIX: t
:END:
* Release Notes
:PROPERTIES:
:ALT_TITLE: Releases
:DESCRIPTION: Release Notes History
:APPENDIX: t
:END:
#+CINDEX: release notes
#+CINDEX: version history
This appendix records the primary changes in each release of
org-trello. Please see the [[https://github.com/org-trello/org-trello][repository]] on GitHub for a more detailed
history.

#+INCLUDE: release-notes.org
